name: Pipelines - Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.5.0

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Create Git tag
        uses: mathieudutour/github-tag-action@v4.6
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Deploy Pages
        uses: devmasx/merge-branch@v1.3.0
        if: github.ref == 'refs/heads/main'
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}